from app.ml.models.disease_cnn import DiseaseCNN
from app.ml.models.pest_detector import PestDetector
from app.ml.models.plant_segmentation import PlantSegmentation
from app.ml.models.growth_stage_classifier import GrowthStageClassifier
from app.ml.models.yield_predictor import YieldPredictor
from app.ml.models.soil_analyzer import SoilAnalyzer
from app.ml.models.weed_detector import WeedDetector
from app.ml.models.nutrient_deficiency import NutrientDeficiency
from app.ml.models.ensemble_model import EnsembleModel
